CREATE TABLE IF NOT EXISTS SEG_MENU(
	ID INT PRIMARY KEY,
	JVERSION INT,
	NOME VARCHAR (50) NOT NULL,
	ID_SEG_MENU_PAI INT,
	ID_SEG_APLICACAO INT NOT NULL
	--FOREIGN KEY (ID_SEG_APLICACAO) REFERENCES ID_SEG_APLICACAO
);
